filebeat.inputs:
  - type: filestream
    id: default-filestream
    paths:
      - /var/jenkins_home/jobs/*/builds/*/log

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      containers:
        - names:
            - bakery-app

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"
